haiwen/seafile-admin-docs

manual/deploy/README.md

Correct minor typo

---

manual/deploy/deploy_seafile_behind_nat.md

Changed "accroding" to "according."

Minor spelling correction

---

manual/maintain/seafile_fsck.md

Followup for https://github.com/haiwen/seafile/pull/1161

curropted => corrupted

---

manual/deploy/deploy_seafile_behind_nat.md

[Issue](https://github.com/haiwen/seafile-admin-docs/issues/23)

Correct HTTPS Default Port

---

manual/changelog.md
manual/deploy/deploy_with_nginx.md
manual/deploy_pro/download_and_setup_seafile_professional_server.md
manual/overview/components.md

* Added an introductory note elaborating on requirements
* Added installation of nginx
* Streamlined description of nginx configuration
-> Modified instructions successfully tested on Debian 10
Some minor edits in the changelog overview page and components

Rewrite of install instructions for Seafile behind nginx

---

manual/docker/pro-edition/deploy_onlyoffice_with_docker.md

Should be `local-production-linux.json` in the `volumes` section.

Add a missing dash in compose file

---

manual/deploy/shibboleth_config_v6.3.md

update shibboleth links

---

manual/deploy/oauth.md
manual/deploy/only_office.md

domain.com is an existing domain and owned by a company.
example.com is better: https://www.iana.org/domains/reserved

use example.com instead of domain.com

---

manual/docker/non_docker_to_docker.md

Proposal for https://github.com/haiwen/seafile-admin-docs/issues/113

securing the host database

---

manual/extension/webdav.md

if I got something wrong, I am happy to learn.

seatable -> seafile; http/:?

---

manual/config/seafile-conf.md
mkdocs.yml

This reverts commit 049b57dfaf96d53f559363167fec65599135dfa4.

Revert "Delete notification server from doc (#131)"

---

manual/maintain/seafile_gc.md

```bash
sed -i \
's/librareis/libraries/g' \
$(find . -type f)
```

docs: mispelling

---

manual/client/seafile_cli.md

fix a markdown error

---

manual/deploy_pro/adfs.md
manual/deploy_pro/config_seafile_with_ADFS.md
manual/docker/docker-compose/ce/10.0/docker-compose.yml
manual/docker/docker-compose/ce/11.0/docker-compose.yml
manual/docker/docker-compose/pro/10.0/docker-compose.yml
manual/docker/docker-compose/pro/11.0/docker-compose.yml
manual/docker/docker-compose/pro/7.1_8.0/docker-compose.yml
manual/docker/docker-compose/pro/9.0/docker-compose.yml
manual/docker/non_docker_to_docker.md
manual/extra_setup/sdoc/docker-compose.yml

"required" means "mandatory", "not optional", and I assume that's what the maintainers meant :)

fix typo: replace "requested" by "required"

---

manual/deploy/https_with_nginx.md

* fixed a few broken links on page https://manual.seafile.com/deploy/https_with_nginx/
* prettified a few formatting typos

fix a few broken links, prettified a few formatting typos

---

manual/deploy/ldap_in_11.0.md
manual/deploy_pro/ldap_in_11.0.md

Typo here
Refer to code: https://github.com/haiwen/seahub/blob/a0350a5bb4cfbd00b05846ad00b98241b65ae188/seahub/base/accounts.py#L48

Fix attr name in LDAP description

---

manual/docker/deploy_seafile_with_docker.md

Removed hyphen for docker compose manual.

Update deploy_seafile_with_docker.md - Docker Compose documentation

---

manual/upgrade/upgrade_docker.md

Just a small typo obsolote -> obsolete

Fix obsolete typo in upgrade docker

---

manual/upgrade/upgrade_docker.md

Add a download link for seadoc.yml in the upgrade documentation.

Add a download link for seadoc.yml in the upgrade documentation.

---

manual/extension/libreoffice_online.md
manual/extension/only_office.md

Independently deploy OnlyOffice and Collabora

Independently deploy OnlyOffice and Collabora
